language: node_js
node_js:
  - node # latest stable Node.js release

sudo: false

notifications:
  email:
    recipients:
      - eric@konklone.com
      - adelevie@gmail.com
    on_success: change
    on_failure: change

branches:
  only:
    - master
